config/routes.rb
Rails.application.routes.draw do
	root to: 'home#index'

	devise_for :users, controllers: {registrations: 'registrations', sessions: 'sessions'}

	get 'faq' => 'home#faq'
	get 'about' => 'home#about'
	get 'search' => 'home#search'
	get 'admin' => 'home#admin'

	resources :styles
	resources :services
	resources :hair_properties
	resources :locations
	resources :ethnicities
	resources :schedules
	resources :events
	resources :memberships
	resources :organizations
	resources :barber_styles, only: [:create]
	resources :profiles, only: [:show, :update]
	resources :user_favorites, only: [:create, :destroy], path: 'favorites'
	resources :subscriptions, only: [:new, :create]
	resources :barbers, only: [:show]
	resources :endorsements, only: [:create, :destroy]

	get 'admin' => 'admin#dashboard'
	get 'calendar' => 'barbers#calendar'
	get 'schedule' => 'barbers#schedule'
	get 'appointments' => 'home#appointments'

	match 'pricing' => 'subscriptions#new', via: :get
	match 'favorites' => 'user_favorites#index', via: :get
	match 'profile' => 'profiles#edit', via: :get
	match 'dashboard' => 'organizations#edit', via: :get
	match 'stripe/hooks' => 'stripe_hooks#receive_webhooks', via: :post
	match 'hooks' => 'hooks#dispatch_event', via: :post

	put 'change_hair_properties' => 'hair_properties#change'

	post 'schedules' => 'barbers#create_schedule'
	post 'barber_services' => 'barber_services#create'
	post 'delete_favorite' => 'user_favorites#delete_favorite'
	post 'delete_barber_style' => 'barber_styles#delete_barber_style'
	post 'delete_barber_service' => 'barber_services#delete_barber_service'
	post 'delete_endorsement' => 'endorsements#delete_endorsement'

end

app/models/hair_property.rb
# == Schema Information
#
# Table name: hair_properties
#
#  id          :integer          not null, primary key
#  type        :string
#  name        :string
#  description :text
#

class HairProperty < ActiveRecord::Base
	has_many :client_hair_properties, inverse_of: :hair_property
end

app/controllers/hair_properties_controller.rb
class HairPropertiesController < ApplicationController
	before_action :set_hair_property, only: [:show, :edit, :update, :destroy]
	skip_before_action :verify_authenticity_token
	authorize_resource except: [:change]

	def new
		@hair_property = HairProperty.new
		@types = ["HairStyle", "HairWidth", "HairDensity"]
	end

	def edit
	end

	def index
		@hair_types = HairType.all
		@hair_widths = HairWidth.all
		@hair_densities = HairDensity.all
	end

	def create
		@hair_property = HairProperty.new(hair_property_params)

		respond_to do |format|
			if @hair_property.save
				flash[:success] = 'Hair Property was successfully created.'
				format.html { redirect_to @hair_property }
				format.json { render :show, status: :created, location: @hair_property }
			else
				format.html { render :new }
				format.json { render json: @hair_property.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		respond_to do |format|
			if @hair_property.update(hair_property_params)
				flash[:success] = 'Hair Property was successfully updated.'
				format.html { redirect_to @hair_property }
				format.json { render :show, status: :ok, location: @hair_property }
			else
				format.html { render :edit }
				format.json { render json: @hair_property.errors, status: :unprocessable_entity }
			end
		end
	end

	def change
		profile = current_user.profile
		hair_properties = HairProperty.where(type: params[:prop_type])

		# Destroy all client hair properties that belong to this user
		ClientHairProperty.where(profile: profile, hair_property_id: hair_properties).delete_all
		ClientHairProperty.create(profile: profile, hair_property_id: params[:hair_property_id])

		render json: { status: 200}
	end

	def destroy
			@hair_property.destroy
		respond_to do |format|
			flash[:success] = 'Hair Property was successfully destroyed.'
			format.html { redirect_to hair_properties_path }
			format.json { head :no_content }
		end
	end

	private
	def set_hair_property
		@hair_property = HairProperty.find(params[:id])
		@types = ["HairStyle", "HairWidth", "HairDensity"]
	end

	def hair_property_params
		params.require(:hair_property).permit(:name,:description,:type)
	end
end

app/views/hair_properties/_form.haml
.col-md-12
	%br
	%br
	= form_for(hair_property, url: hair_property_path(hair_property)) do |f|
		- if hair_property.errors.any?
			#error_explanation
				%h2
					= pluralize(hair_property.errors.count, "error")
					prohibited this hair_property from being saved:
				%ul
					- hair_property.errors.full_messages.each do |message|
						%li= message
		.col-md-12
			.hair_property-field
				="Name"
				%br
				= f.text_field :name, autofocus: true, class: 'input hair_property-input'
				%br
				%br
			.hair_property-field
				="Description"
				%br
				= f.text_area :description, autocomplete: "off", class: 'input hair_property-input'
				%br
				%br
			.hair_property-field
				="Property Type"
				%br
				=f.select(:type, @types, {include_blank: "Select a type"}, {class: 'input hair_property-input'})
				%br
				%br
		.actions
			= f.submit class: 'brand-btn med-btn'
	= link_to 'Back', hair_properties_path

app/views/hair_properties/edit.haml
#cms
	.container
		.form
			%h1=" Editing #{@hair_property.name}"
			= render 'form', hair_property: @hair_property

app/views/hair_properties/index.haml
#cms
	.container
		%h1 Hair Properties
		= link_to 'New Hair Property', new_hair_property_path, class: 'edit'
		.hair_properties
			%h3 Hair Types:
			- @hair_types.each do |hair_type|
				= link_to edit_hair_property_path(hair_type), class: 'edit' do
					.fa.fa-pencil.edit
					%span.hair_type=hair_type.name
				-# = link_to hair_property_path(hair_type), method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete-hair_property' do
				-# 	%span.fa.fa-times.delete
				%br
			%h3 Hair Widths:
			- @hair_widths.each do |hair_width|
				= link_to edit_hair_property_path(hair_width), class: 'edit' do
					.fa.fa-pencil.edit
					%span.hair_width=hair_width.name
				-# = link_to hair_property_path(hair_width), method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete-hair_property' do
				-# 	%span.fa.fa-times.delete
				%br
			%h3 Hair Densities:
			- @hair_densities.each do |hair_density|
				= link_to edit_hair_property_path(hair_density), class: 'edit' do
					.fa.fa-pencil.edit
					%span.hair_density=hair_density.name
				-# = link_to hair_property_path(hair_density), method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete-hair_property' do
				-# 	%span.fa.fa-times.delete
				%br

app/views/hair_properties/new.haml
#cms
	.container
		.form
			%h1 New Hair Property
			= render 'form', hair_property: @hair_property