config/routes.rb
Rails.application.routes.draw do
	root to: 'home#index'

	devise_for :users, controllers: {registrations: 'registrations', sessions: 'sessions'}

	get 'faq' => 'home#faq'
	get 'about' => 'home#about'
	get 'search' => 'home#search'
	get 'admin' => 'home#admin'

	resources :styles
	resources :services
	resources :hair_properties
	resources :locations
	resources :ethnicities
	resources :schedules
	resources :events
	resources :memberships
	resources :organizations
	resources :barber_styles, only: [:create]
	resources :profiles, only: [:show, :update]
	resources :user_favorites, only: [:create, :destroy], path: 'favorites'
	resources :subscriptions, only: [:new, :create]
	resources :barbers, only: [:show]
	resources :endorsements, only: [:create, :destroy]

	get 'admin' => 'admin#dashboard'
	get 'calendar' => 'barbers#calendar'
	get 'schedule' => 'barbers#schedule'
	get 'appointments' => 'home#appointments'

	match 'pricing' => 'subscriptions#new', via: :get
	match 'favorites' => 'user_favorites#index', via: :get
	match 'profile' => 'profiles#edit', via: :get
	match 'dashboard' => 'organizations#edit', via: :get
	match 'stripe/hooks' => 'stripe_hooks#receive_webhooks', via: :post
	match 'hooks' => 'hooks#dispatch_event', via: :post

	put 'change_hair_properties' => 'hair_properties#change'

	post 'schedules' => 'barbers#create_schedule'
	post 'barber_services' => 'barber_services#create'
	post 'delete_favorite' => 'user_favorites#delete_favorite'
	post 'delete_barber_style' => 'barber_styles#delete_barber_style'
	post 'delete_barber_service' => 'barber_services#delete_barber_service'
	post 'delete_endorsement' => 'endorsements#delete_endorsement'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	include ApplicationHelper

	def index
	end

	def faq
	end

	def about
	end

	def appointments
		@events = Event.where(client_id: current_user.id)
	end

	def search
		@signedIn = current_user ? true : false

		if current_user
			@user_avatar = @signedIn ? current_user.default_avatar : '/assets/default-avatar.png'

			# Temporarily removing public check
			# @barbers = get_react_barber_objects(Barber.all.select{|b| b.public?})
			@barbers = get_react_barber_objects(Barber.all)

			if current_user
				@barbers = filterBarbers(@barbers)
			else
				@barbers = @barbers.shuffle
			end

			@barbers.each do |barber|
				barber[:barberStyles] = barber[:barberStyles].slice(0,3)
			end

			@featured_barber = @barbers[0]
			@barbers = @barbers - [@featured_barber]
			@profile_id = current_user.profile.id
			@style = current_user.current_style_id.present? ? current_user.style.name : "Choose your Style"
			@location = current_user.location.present? ? current_user.location : "Choose your Location"
			# @price = [1,2,3,4].sample
		else
			redirect_to new_user_registration_path, alert: "Please create your account to access this page."
		end

	end

	def filterBarbers(barbers)
		newBarbers = []

		results = get_top_barbers_by_style(barbers)
		top_style_barbers = results.pluck(:barber)

		top_style_barbers.each do |tsb|
			newBarbers << tsb
		end
		barbers = barbers - top_style_barbers

		barbers = barbers.sort_by {|b| b[:price]}
		barbers.each do |b|
			newBarbers << b
		end

		newBarbers
	end

	def get_top_barbers_by_style(barbers)
		puts "Barbers: #{barbers}"
		current_style_name = current_user.profile.current_style_name
		results = []
		barbers.each do |b|
			matching_styles = b[:barberStyles].select {|bs| bs[:name] == current_style_name }
			results << {barber: b, matching_style: matching_styles[0]} if matching_styles.present?
		end

		results.sort_by {|r| r[:matching_style][:endorsements]}.reverse
	end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.haml
#about
	.container
		%h1 About

app/views/home/admin.haml
#admin
	.container
		%h1
			Admin Dashboard
		%h3 Styles
		.styles
			=link_to new_style_path, class: 'med-btn brand-btn light-brand-btn cms-btn' do
				%span.fa.fa-plus-circle
				="New Style"
			%br
			%br

			=link_to styles_path, class: 'med-btn brand-btn light-brand-btn cms-btn' do
				%span.fa.fa-pencil
				="Edit Existing Styles"


		%h3 Services
		.services
			=link_to new_service_path, class: 'med-btn brand-btn light-brand-btn cms-btn' do
				%span.fa.fa-plus-circle
				="New Service"
			%br
			%br

			=link_to services_path, class: 'med-btn brand-btn light-brand-btn cms-btn' do
				%span.fa.fa-pencil
				="Edit Existing Services"

		%h3 Hair Properties
		.services
			=link_to new_hair_property_path, class: 'med-btn brand-btn light-brand-btn cms-btn' do
				%span.fa.fa-plus-circle
				="New Hair Property"
			%br
			%br

			=link_to hair_properties_path, class: 'med-btn brand-btn light-brand-btn cms-btn' do
				%span.fa.fa-pencil
				="Edit Existing Hair Properties"

		%h3 Locations
		.services
			=link_to new_location_path, class: 'med-btn brand-btn light-brand-btn cms-btn' do
				%span.fa.fa-plus-circle
				="New Location"
			%br
			%br

			=link_to locations_path, class: 'med-btn brand-btn light-brand-btn cms-btn' do
				%span.fa.fa-pencil
				="Edit Existing Locations"

		%h3 Ethnicities
		.services
			=link_to new_ethnicity_path, class: 'med-btn brand-btn light-brand-btn cms-btn' do
				%span.fa.fa-plus-circle
				="New Ethnicity"
			%br
			%br

			=link_to ethnicities_path, class: 'med-btn brand-btn light-brand-btn cms-btn' do
				%span.fa.fa-pencil
				="Edit Existing Ethnicities"

app/views/home/appointments.haml
.container
	.appointments-container
		%h1
			Your appointments:
		-@events.each do |event|
			.appointments-list.col-md-12{style:'text-align:left'}
				.col-md-2
					=link_to barber_path(event.barber) do
						=image_tag event.barber.default_avatar, width: 35, class: 'avatar'
						=event.barber.name
				.col-md-2
					=local_time(event.try(:start_time), '%a, %b %e')
				.col-md-2
					From:
					=local_time(event.try(:start_time), '%l:%M %p')
				.col-md-2
					To:
					=local_time(event.try(:end_time), '%l:%M %p')
				.col-md-2
					="Style: #{event.style.try(:name).try(:capitalize)}"
				.col-md-2
					Extra Services:
					%br
					-services = event.try(:services).try(:split, ',')
					-services.try(:each) do |service|
						%li=service

app/views/home/faq.html.haml
#about
	.container
		%h1 Frequently Asked Questions

app/views/home/index.html.haml
#home
	#banner
		.content.initial-fade-in-short
			.text
				%h1
					%p.black-white.head A PERFECT HAIRCUT EXPERIENCE?
					%p.black-white.subhead ALLDID MAKES IT EASY.
				%h2
					%p Alldid finds your perfect barber.
					%p You'll be matched to someone who specializes in your hairstyle.
					%p Then, view their contact info, social media, and more.

			.buttons.initial-fade-in-long
				.banner-btns
					=link_to search_path, class: 'white-btn large-btn' do
						Find your Barber Now
						%span

	#how-it-works
		.content
			%h3.fade-in
				HOW IT WORKS
				%hr.half-hr.fade-in
			.columns
				.column.fade-in
					.fa.fa-edit
					%h3 Personalize
					%h4 Create your custom hair profile
					%p
						We personalize your individual hair profile, style, and preferences. This only takes a minute.
						-# We personalize your individual hair profile, style, and preferences. These criteria then get plugged into our matching algorithm to find you the most proficient barber for your needs.
				.column.fade-in
					.fa.fa-users
					%h3 Match
					%h4 Choose your barber
					%p
						Once we match you with your recommended barbers, you get to view their profiles and select your favorites.
						-# Once we match you with your recommended barbers, you get to view their profiles and select your favorite. They'll be able to view yours as well, so they know your hair before you get there!
				.column.fade-in
					.fa.fa-calendar
					-# %h3 Book
					%h3 Contact
					-# %h4 Book your appointment online
					%h4 Get connected
					%p
						-# View vacant time slots in your barber's schedule with ease. Book your appointment with just a few clicks. No more waiting in line and no more tedious phone calls.
						Your barber will be able to view your profile as well, so they know your hair before you get there!

app/views/home/search.haml
#search
	=react_component('SearchContainer', props: {barbers: @barbers, featured: @featured_barber, profileId: @profile_id, style: @style, userLocation: @location, userAvatar: @user_avatar, links: true, signedIn: @signedIn }, prerender: false)