config/routes.rb
Rails.application.routes.draw do
	root to: 'home#index'

	devise_for :users, controllers: {registrations: 'registrations', sessions: 'sessions'}

	get 'faq' => 'home#faq'
	get 'about' => 'home#about'
	get 'search' => 'home#search'
	get 'admin' => 'home#admin'

	resources :styles
	resources :services
	resources :hair_properties
	resources :locations
	resources :ethnicities
	resources :schedules
	resources :events
	resources :memberships
	resources :organizations
	resources :barber_styles, only: [:create]
	resources :profiles, only: [:show, :update]
	resources :user_favorites, only: [:create, :destroy], path: 'favorites'
	resources :subscriptions, only: [:new, :create]
	resources :barbers, only: [:show]
	resources :endorsements, only: [:create, :destroy]

	get 'admin' => 'admin#dashboard'
	get 'calendar' => 'barbers#calendar'
	get 'schedule' => 'barbers#schedule'
	get 'appointments' => 'home#appointments'

	match 'pricing' => 'subscriptions#new', via: :get
	match 'favorites' => 'user_favorites#index', via: :get
	match 'profile' => 'profiles#edit', via: :get
	match 'dashboard' => 'organizations#edit', via: :get
	match 'stripe/hooks' => 'stripe_hooks#receive_webhooks', via: :post
	match 'hooks' => 'hooks#dispatch_event', via: :post

	put 'change_hair_properties' => 'hair_properties#change'

	post 'schedules' => 'barbers#create_schedule'
	post 'barber_services' => 'barber_services#create'
	post 'delete_favorite' => 'user_favorites#delete_favorite'
	post 'delete_barber_style' => 'barber_styles#delete_barber_style'
	post 'delete_barber_service' => 'barber_services#delete_barber_service'
	post 'delete_endorsement' => 'endorsements#delete_endorsement'

end

app/models/style.rb
# == Schema Information
#
# Table name: styles
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  url         :string
#

class Style < ActiveRecord::Base
	mount_uploader :url, StyleUploader
	
	has_many :events, inverse_of: :style

end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
	before_action :set_style, only: [:show, :edit, :update, :destroy]
	authorize_resource

	def new
		@style = Style.new
	end

	def edit
	end

	def index
		@styles = Style.all
	end

	def create
		@style = Style.new(style_params)

		respond_to do |format|
			if @style.save
				flash[:success] = 'Style was successfully created.'
				format.html { redirect_to styles_path }
				format.json { render :show, status: :created, location: @style }
			else
				format.html { render :new }
				format.json { render json: @style.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		respond_to do |format|
			if @style.update(style_params)
				flash[:success] = 'Style was successfully updated.'
				format.html { redirect_to styles_path }
				format.json { render :show, status: :ok, location: @style }
			else
				format.html { render :edit }
				format.json { render json: @style.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
			@style.destroy
		respond_to do |format|
			flash[:success] = 'Style was successfully destroyed.'
			format.html { redirect_to styles_path }
			format.json { head :no_content }
		end
	end

	private
	def set_style
		@style = Style.find(params[:id])
	end

	def style_params
		params.require(:style).permit(:name, :description, :url, :url_cache)
	end

end

app/views/styles/_form.haml
.col-md-12
	%br
	%br
	= form_for(style) do |f|
		- if style.errors.any?
			#error_explanation
				%h2
					= pluralize(style.errors.count, "error")
					prohibited this style from being saved:
				%ul
					- style.errors.full_messages.each do |message|
						%li= message
		.col-md-12
			.style-field
				="Name"
				%br
				= f.text_field :name, autofocus: true, class: 'input style-input'
				%br
				%br
			.style-field
				="Description"
				%br
				= f.text_field :description, autocomplete: "off", class: 'input style-input'
				%br
				%br
			.style-field{style: 'text-align: center'}
				="Picture"
				%br
				= f.file_field :url, autocomplete: "off", style: 'text-align: center'
				%br
				%br
		.actions
			= f.submit class: 'brand-btn med-btn'
	= link_to 'Back', styles_path

app/views/styles/edit.haml
#cms
	.container
		.form
			%h1=" Editing #{@style.name}"
			= render 'form', style: @style

app/views/styles/index.haml
#cms
	.container
		%h1 Styles
		= link_to 'New Style', new_style_path, class: 'edit'
		.styles
			%h3 Styles:
			- @styles.each do |style|
				= link_to edit_style_path(style), class: 'edit' do
					.fa.fa-pencil.edit
					%span.style=style.name
				-# = link_to style, method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete-style' do
				-# 	%span.fa.fa-times.delete
				%br

app/views/styles/new.haml
#cms
	.container
		.form
			%h1 New Style
			= render 'form', style: @style