config/routes.rb
Rails.application.routes.draw do
	root to: 'home#index'

	devise_for :users, controllers: {registrations: 'registrations', sessions: 'sessions'}

	get 'faq' => 'home#faq'
	get 'about' => 'home#about'
	get 'search' => 'home#search'
	get 'admin' => 'home#admin'

	resources :styles
	resources :services
	resources :hair_properties
	resources :locations
	resources :ethnicities
	resources :schedules
	resources :events
	resources :memberships
	resources :organizations
	resources :barber_styles, only: [:create]
	resources :profiles, only: [:show, :update]
	resources :user_favorites, only: [:create, :destroy], path: 'favorites'
	resources :subscriptions, only: [:new, :create]
	resources :barbers, only: [:show]
	resources :endorsements, only: [:create, :destroy]

	get 'admin' => 'admin#dashboard'
	get 'calendar' => 'barbers#calendar'
	get 'schedule' => 'barbers#schedule'
	get 'appointments' => 'home#appointments'

	match 'pricing' => 'subscriptions#new', via: :get
	match 'favorites' => 'user_favorites#index', via: :get
	match 'profile' => 'profiles#edit', via: :get
	match 'dashboard' => 'organizations#edit', via: :get
	match 'stripe/hooks' => 'stripe_hooks#receive_webhooks', via: :post
	match 'hooks' => 'hooks#dispatch_event', via: :post

	put 'change_hair_properties' => 'hair_properties#change'

	post 'schedules' => 'barbers#create_schedule'
	post 'barber_services' => 'barber_services#create'
	post 'delete_favorite' => 'user_favorites#delete_favorite'
	post 'delete_barber_style' => 'barber_styles#delete_barber_style'
	post 'delete_barber_service' => 'barber_services#delete_barber_service'
	post 'delete_endorsement' => 'endorsements#delete_endorsement'

end

app/models/organization.rb
# == Schema Information
#
# Table name: organizations
#
#  id               :integer          not null, primary key
#  location         :string
#  zip              :integer
#  user_id          :integer
#  name             :string
#  stripe_reference :string
#  status           :string
#  created_at       :datetime
#  updated_at       :datetime
#  code             :string
#  subscription_id  :integer
#  phone            :string
#

class Organization < ActiveRecord::Base
	has_many :memberships
	has_many :users, through: :memberships
	after_create :create_code
	belongs_to :user
	belongs_to :subscription

	def create_code
		self.code = SecureRandom.random_number(36**12).to_s(36).rjust(12, "0")
		self.save
	end

	def has_room?
		member_count < max_members
	end

	def max_members
		Float::INFINITY
	end

	def member_count
		self.memberships.count
	end

	def active?

	end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
	before_action :set_organization, only: [:edit, :update]
	skip_before_action :verify_authenticity_token

	def edit
	end

	def update
		respond_to do |format|
			if @organization.update(organization_params)
				format.html { redirect_to '/dashboard', notice: 'Organization was successfully updated.' }
				format.json { render json: @organization }
			else
				format.html { render '/dashboard' }
				format.json { render json: @organization.errors, status: :unprocessable_entity }
			end
		end
	end

	private
	def set_organization
		@organization = Organization.find_by(user: current_user)
	end

	def organization_params
		params.require(:organization).permit(:name, :phone)
	end

end

app/views/organizations/edit.haml
#cms
	#organization.container
		-organization_name = @organization.name.present? ? @organization.name : "your barbershop"
		-organization_phone = @organization.phone.present? ? @organization.phone : "your phone number"
		.section-container
			=react_component "OrganizationInput", props: {organization: @organization, orgName: organization_name, orgPhone: organization_phone}, prerender: false

		.section-container
			.links-container
				.header="Your invite link:"
				%button#organization-link-button.brand-btn{ 'data-clipboard-action' => 'copy', 'data-clipboard-target' => '#organization-link-text'}
					Copy link
				%span#organization-link-text= "#{request.host}/?invite=#{@organization.code}"
				%br
				%br
				.grey-text="Copy this link and give it to people you'd like to invite to your barber shop."

		.section-container
			.header="Your members:"
			.members-list
				.grey-text="You currently have #{pluralize((@organization.memberships.count - 1), 'member')} in your barber shop."
				%br
				-if @organization.memberships.any?
					-count = 1
					-@organization.memberships.each do |membership|
						-unless membership.user == current_user
							.org-member
								= membership.user.email if membership.user
								=link_to membership_path(membership), method: :delete, data: { confirm: "Are you sure?" }, class: 'delete-membership' do
									.fa.fa-times
								%br
								-# .view-schedule{"data-toggle": "collapse", "data-target": "#member-schedule-#{count}"}
								-# 	="View Schedule"
								-# 	%span.fa.fa-chevron-down
								-# %br
								-# .collapse{id: "member-schedule-#{count}"}
								-# 	-if membership.user.events.any?
								-# 		-membership.user.events.each do |event|
								-# 			.appointments-list.col-md-12{style:'text-align:left'}
								-# 				.col-md-2
								-# 					=link_to profile_path(event.client) do
								-# 						=image_tag event.client.default_avatar, width: 35, class: 'avatar'
								-# 						=event.client.name
								-# 				.col-md-2
								-# 					=event.start_time.strftime('%a, %b %-d')
								-# 				.col-md-2
								-# 					="From: #{event.start_time.strftime('%I:%M %p')}"
								-# 				.col-md-2
								-# 					="To: #{event.end_time.strftime('%I:%M %p')}"
								-# 				.col-md-2
								-# 					=event.style.try(:name).try(:capitalize)
								-# 				.col-md-2
								-# 					Services
								-# 	-else
								-# 		.grey-text="#{membership.user.name} has no appointments."
								-#
								-# -count += 1